### ISSUE TITLE
As a user i would like to be able to add dynamic dates to my mock.

### ISSUE THREAD

**Issue by rrijnberk** [mdasberg/grunt-ng-apimock#10]
It would be nice if we could add a flexible date. Preferably something which can be formatted. I was thinking something along the lines of:
" date: X d(ays) X m(onths) X y(ears) in the [ future | past ] ( as [ json | dd-MM-yyyy ] ) "

so "date: 1 day in the future as json" means tomorrow represented as "2015-11-24T00:00:00.000Z" if today is November 23rd 2015.

Whereas "date: 1 months 4 days in the past as dd-MM-yyyy" would be represented as "27-02-2015" if today is March 3rd 2015.

**Comment by mdasberg** [comment]
@rrijnberk see: https://github.com/mdasberg/grunt-ng-apimock#howto-use-global-variables
